### ISSUE TITLE
Wrong git repo in SOME ipynb---- https://github.com/samthiele/hylite_demo2.git

### ISSUE THREAD

**Issue by air55555** [hifexplo/hylite#10]
01_The_basics.ipynb
01_The_basics.ipynb_Notebook unstarred
Changes will not be saved
Setup GoogleColab environment
Install hylite and download tutorial data

[1]
3s
! git clone https://github.com/samthiele/hylite_demo2.git
account_circle
Cloning into 'hylite_demo2'...

**Comment by samthiele** [comment]
Thanks for the heads-up. This should be fixed now?

**Comment by air55555** [comment]
Sure not, sometimes. Low low priority)

**Comment by samthiele** [comment]
Is done; please check everything works for you :-)
