### ISSUE TITLE
Partially broken tuturial 04_UndergroundMapping.ipynb ?

### ISSUE THREAD

**Issue by air55555** [hifexplo/hylite#11]
The tutorial 04_UndergroundMapping.ipynb  located at doc section [Yet another introduction from the VGC conference](https://drive.google.com/drive/folders/1_gDRMrccNG3OMyIPYy0mkpkbN6nn92OW?usp=sharing)  contains part of the info.
As per [VGC  workshop presentation ](https://docs.google.com/presentation/d/1cF6z0qVI8GDqw42BhsxySivdg-OIL_rZj3g67tp25_I/edit#slide=id.p12)
04_UndergroundMapping.ipynb  expected to contain these topics : . 
   Work with spectral libraries
   More interesting data visualization
   Machine learning (regression) models
   Locate sensor relative to point cloud
   Back-project data (or results) into 3D
But  regression models is the last topic presented. Also actual ipynb file name is 10_MineralMapping.ipynb . Maybe just wrong http link in the gdrive folder.

**Comment by samthiele** [comment]
Thanks, I've adjusted the power point; the other aspects (e.g., back-projection of data to the point cloud) were dropped from this notebook while we were building the workshop (and are documented in the main tutorial series anyway).

**Comment by air55555** [comment]
Thank you Sam for fast update . 
I am interested in " Locate sensor relative to point cloud " and alignment of point cloud with hsi image by points - align_to_cloud_manual function of hylite . Seems i will use main tutorial series than , if there is no  additional tutorial on that .
