### ISSUE TITLE
Opening image files

### ISSUE THREAD

**Issue by grantboxer** [hifexplo/hylite#7]
I am a new user to Jupyter notebook and am trying to open the image and pointcloud files in your tutorial 01_The_basics (line 31) but I can't seem to get the syntax correct.

I have used this "image = io.load('/test_data/image.hdr' )" plus a variety of other combinations without success.

Any suggestions?
Cheers Grant, Western Australia

**Comment by grantboxer** [comment]
This is the error message.
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_22420\1139806743.py in <module>
      3 
      4 # open an ENVI image
----> 5 image = io.load('/test_data/image.hdr' )
      6 
      7 # open a .ply point cloud

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\hylite\io\__init__.py in load(path)
    133     """
    134 
--> 135     assert os.path.exists( path ), "Error: file %s does not exist." % path
    136 
    137     # load file formats with no associated header

AssertionError: Error: file /test_data/image.hdr does not exist.

**Comment by samthiele** [comment]
Hi Grant, 

This error means that the file path you are giving the `io.open` function is invalid (file not found). Are you running your notebook locally or on the GoogleColab? 

https://drive.google.com/drive/folders/1hkr4gtP1OY_PIK7cynl3dWd3sYi_9s5F?usp=drive_link

**Comment by grantboxer** [comment]
Hi Sam,

I am running it locally and the file location is "C:\Users\boxer\Hylite\hylite_demo2\test_data".

I seem to have to change the slash direction as well. Should I try running it under GoogleColab?

**Comment by grantboxer** [comment]
Trying Colab now, and it doesn't load the test image. Should I be pointing file location to somewhere else?

# open an ENVI image
image = io.load('C:/Users/boxer/Hylite/hylite_demo2/test_data/image.hdr' )

**Comment by grantboxer** [comment]
Do you know of anyone using Hylite for EnMAP or PRISMA hyperspectral imagery? That is my main aim at seeing what Hylite can do for me.

**Comment by grantboxer** [comment]
Any chance of an example to get me started?

**Comment by sandralorenz268** [comment]
Hi,
for loading PRISMA data we just uploaded an example notebook to the [hylite Tutorial Notebooks](https://drive.google.com/drive/folders/1hkr4gtP1OY_PIK7cynl3dWd3sYi_9s5F?usp=drive_link).

**Comment by grantboxer** [comment]
Thank you, I will take a look.

**Comment by grantboxer** [comment]
Greetings,

 

I am having problems with tutorial notebook 6. It doesn’t seem to like the quick_plot command.

 

fig,ax = rgb.quick_plot( (0,1,2), image.header.get_camera(0), vmin=0., vmax=1., fill_holes=True, despeckle=False )

 

Any thoughts?

 

Cheers Grant

 

Grant Boxer

Consultant Geologist (FAIG R.P. Geo)

Perth, Western Australia

Email: ***@***.*** ***@***.***> 

Mobile: 0418 954 059

Skype: grantboxer

Website: https://grantboxer.github.io
