### ISSUE TITLE
Plot problem

### ISSUE THREAD

**Issue by grantboxer** [hifexplo/hylite#8]
I get an error message on this line, any thoughts?

Cheers Grant

rgb.quick_plot( (0,1,2), image.header.get_camera(0), vmin=0., vmax=1., ax=a)

TypeError                                 Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_9336\3603358142.py](https://file+.vscode-resource.vscode-cdn.net/e%3A/Dropbox/RemoteSensing/Hyperspectral/HyliteTutorials/~/AppData/Local/Temp/ipykernel_9336/3603358142.py) in <module>
      7                             )
      8     a.set_title("Feature %d" % i)
----> 9     rgb.quick_plot( (0,1,2), image.header.get_camera(0), vmin=0., vmax=1., ax=a)
     10     leg.plot(a, pos='lower left', s=(0.2,0.1) ) # plot special colorbar
     11 fig.tight_layout()

TypeError: quick_plot() got multiple values for argument 'ax'

**Comment by samthiele** [comment]
Hi Grant; I suspect the problem is the second argument of the `quick_plot` function. You are passing a camera object (`image.header.get_camera(0)`), which is needed to render hyperclouds (`HyCloud.quick_plot`) but not expected if `HyImage.quick_plot` is called. 

Long story short - assuming `rgb` is an image and not a cloud, try replacing line 9 with:
`rgb.quick_plot( (0,1,2), vmin=0., vmax=1., ax=a)`

**Comment by grantboxer** [comment]
Hi Sam,

 

OK, will try that,

 

Cheers Grant

**Comment by grantboxer** [comment]
Hi Sam,

 

Steadily working my way through using my own PRISMA data in the MWL section.

 

I have now come to this cell,

 

mnf, w = MNF(image, bands=5) # calculate MNF filter from image

fig,ax = rgb.quick_plot((0,1,2)) # map the first 3 bands. Note that these have no physical meaning anymore.

fig.show()

 

and got this message. Any thoughts?

 

ValueError                                Traceback (most recent call last)

~\AppData\Local\Temp\ipykernel_1516\1775767081.py <https://file+.vscode-resource.vscode-cdn.net/e%3A/Dropbox/RemoteSensing/Hyperspectral/HyliteTutorials/~/AppData/Local/Temp/ipykernel_1516/1775767081.py>  in <module>

----> 1 mnf, w = MNF(image, bands=5) # calculate MNF filter from image

      2 fig,ax = rgb.quick_plot((0,1,2)) # map the first 3 bands. Note that these have no physical meaning anymore.

      3 fig.show()

 

ValueError: too many values to unpack (expected 2)

 

Cheers Grant

**Comment by grantboxer** [comment]
Hi Sam,

 

I have worked through the minimum wavelength mapping and it resulted in an “X” file and a “model” file. How do I interpret these two files? One appears to be wavelengths as specified but the other has different set of wavelengths – are these depths of features? See this link for my files from the Cuprite (Nevada area, PRISMA data) – “https://www.dropbox.com/scl/fi/pygzyxtaw14ymwcru5qam/mwl_Cuprite.mwl.zip?rlkey=4tcdb7y19olusoxliep41xihr <https://www.dropbox.com/scl/fi/pygzyxtaw14ymwcru5qam/mwl_Cuprite.mwl.zip?rlkey=4tcdb7y19olusoxliep41xihr&dl=0> &dl=0”.

 

Cheers Grant

**Comment by samthiele** [comment]
Hi Grant, 

Regarding your first error - I made breaking changes recently to the MNF function, which causes your error. Please replace that line of code with:

`mnf, loadings, means = MNF( image, bands=5 )`

(note that the function now returns three values, the MNF results, the band loadings and the band-means. Previously the means were not returned).

On the minimum wavelength mapping - the X file stores the corrected data that was used during minimum wavelength fitting, while the model file contains the resulting gaussian positions, widths and depths. 

Generally it's not recommended to work directly with these files, but instead load the whole directory as a MWL object and then use the `deepest( .. ) `or `closest( ... ) ` functions to retrieve specific features from within it. These will be returned as a HyImage instance with the following bands: depth, position, width_left, width_right. The MWL mapping tutorial here hopefully shows how to do this :-)

https://drive.google.com/file/d/1a_MsDZIdg9-MsbJ1N3tU58tK4A2uZV91/view?usp=sharing

Hope that helps! 

Cheers,
Sam
