### ISSUE TITLE
hylite_demo2 missing

### ISSUE THREAD

**Issue by aloboa** [hifexplo/hylite#9]
The README file states:

> Next steps
> 1. Download and try the example notebooks / tutorials [here](https://github.com/samthiele/hylite_demo2).

but this opens an unknown page.

**Comment by samthiele** [comment]
Hi @aloboa , thanks for the heads up. I've migrated all the tutorials to Google Colab, so you can find them here instead:

https://drive.google.com/drive/folders/1hkr4gtP1OY_PIK7cynl3dWd3sYi_9s5F?usp=drive_link

Clearly I missed one of the links in the readme file; will fix this now.

Cheers,
Sam
